<a href="https://colab.research.google.com/github/sanjai570/MACHINE_LEARNING/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **dimensions and shape**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

# **range function**

In [ ]:
rge = np.arange(1,10)
print(rge)
rge

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# **skip values = step**

In [ ]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

# **linspace and log space**

In [ ]:
lin = np.linspace(0,1,5)
lin

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
log = np.logspace(1,3,3)
log

array([  10.,  100., 1000.])

# **logspace using base**

In [ ]:
logbase=np.logspace(1,3,num=3,base=4)
logbase

array([ 4., 16., 64.])

# **zeros and ones**

In [ ]:
zero = np.zeros(5,dtype=int)
print(zero)
one = np.ones([2,3],dtype=int)
one


[0 0 0 0 0]


array([[1, 1, 1],
       [1, 1, 1]])

# **filling a same value "full"**

In [ ]:
rr = np.full(5,2)
rr

array([2, 2, 2, 2, 2])

In [ ]:
rr = np.full([2,4],7.7)
rr

array([[7.7, 7.7, 7.7, 7.7],
       [7.7, 7.7, 7.7, 7.7]])

# **creating an empty array " empty " - its use grabage value in the memory to fill the values**

In [ ]:
arr = np.empty([2,3])
arr

array([[2.06320056e-315, 0.00000000e+000, 1.24030434e+213],
       [6.01328829e-154, 1.97249690e-153, 2.46959157e-312]])

# **genrating random value**

# rand for float

In [ ]:


arr = np.random.rand(2,3)
arr

array([[0.06956662, 0.01149259, 0.61695105],
       [0.64008225, 0.42393088, 0.57984568]])

# randn for std values with mean of 0

In [ ]:
arr=np.random.randn(2,3)
arr

array([[ 0.73868327, -0.4512945 ,  0.26927176],
       [-0.96538273, -0.03513683,  1.14583545]])

# **randint for integers**

**for single integer**

In [ ]:
arr=np.random.randint(10,100)
arr

50

**for array of values**

In [ ]:
arr=np.random.randint(10,100,size = [2,3])
arr

array([[59, 98, 81],
       [14, 56, 32]])

.



.


.

.

.

## **----------NUMPY DATATYPES AND TYPE CASTING-----------**

# **creating a numpy array mannualy**

In [ ]:
arr = np.array([2,3,4,5,6])
arr

array([2, 3, 4, 5, 6])

In [ ]:
arr = np.array([[2,3,4],[5,6,7]])
arr

array([[2, 3, 4],
       [5, 6, 7]])

# **type casting of list to numpy array**

In [ ]:
lis = ["String",'d',1,2.3]
type(lis)

list

In [ ]:
arr=np.array(lis)
arr

array(['String', 'd', '1', '2.3'], dtype='<U32')

In [ ]:
type(arr)

numpy.ndarray

# **type casting**

**while craeting the array**

In [ ]:
arr = np.array([1,2,3],dtype=np.float64)
arr

array([1., 2., 3.])

**after creating the array **

In [ ]:
new_arr = arr.astype(int)

In [ ]:
new_arr

array([1, 2, 3])

#we cant typecast string to float or int
# "ValueError: could not convert string to float: np.str_('hello')"----->this error will thrown

In [ ]:
arr = np.array(["1","2","3"])
arr.astype(float)

array([1., 2., 3.])

In [ ]:
arr2= np.array(["1","2","3","hello"])
arr2.astype(float)

ValueError: could not convert string to float: np.str_('hello')

# **size and itemsize**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr.size

6

In [ ]:
arr.itemsize

8

# **reshaping ,ravel,flatten--->using this functions in an array**

# **1.reshaping**

In [ ]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
againreshape = reshaped.reshape(3,2)
print(againreshape)

[[1 2]
 [3 4]
 [5 6]]


# **2.ravel**

In [ ]:
raveled = reshaped.ravel()
raveled

array([1, 2, 3, 4, 5, 6])

In [ ]:
raveled[0]=100
raveled

array([100,   2,   3,   4,   5,   6])

In [ ]:
reshaped

array([[100,   2,   3],
       [  4,   5,   6]])

**both ravel and flatten do the same process where as the main this is done in the orginal array**

# **flatten**

In [ ]:
flat = reshaped.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [ ]:
flat[0]=1
flat

array([1, 2, 3, 4, 5, 6])

In [ ]:
reshaped

array([[100,   2,   3],
       [  4,   5,   6]])

^
^
|
**from above we can see the only difference is change of the value in the orginal arrray RAVEL change the orginal array itself but FALTTEN creates a copy of the orginal array and change it in which the orginal array is not changed**

## ARITHMETIC OPERATIONS

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
add = (a+b)
sub = (a-b)
mul = (a*b)
div = (a/b)
intdiv = (a//b)
mod = (a%b)
print(add)

[5 7 9]


# universal functions

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# INDEXING AND SLICING

**1D**

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[0:3])

[1 2 3]


In [ ]:
print(arr[::])

[1 2 3 4 5]


**2d**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:,1:])

[[5 6]
 [8 9]]


# **TAKE**

In [ ]:
arr = np.array([1,2,3.1,4,5])
idx = [0,3]
print(np.take(arr,idx))

[1. 4.]


In [ ]:
for x in np.nditer(arr):
  print(x)

1.0
2.0
3.1
4.0
5.0


In [ ]:
for x in np.ndenumerate(arr):
  print(x)

((0,), np.float64(1.0))
((1,), np.float64(2.0))
((2,), np.float64(3.1))
((3,), np.float64(4.0))
((4,), np.float64(5.0))


# **view vs copy**

In [ ]:
arr = np.array([1,2,3,4,5,6])
view = arr[1:3]
view

array([2, 3])

In [ ]:
view[1]=200
view

array([  2, 200])

In [ ]:
arr

array([  1,   2, 200,   4,   5,   6])

In [ ]:
copy = arr[1:3].copy()
copy

array([  2, 200])

In [ ]:
copy[1]=3

In [ ]:
copy

array([2, 3])

In [ ]:
arr

array([  1,   2, 200,   4,   5,   6])

# **TRANSPOSE**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])


In [ ]:
copy.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

# **swap axes**

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]]])
arr.shape

(1, 2, 3)

In [ ]:
swap = np.swapaxes(arr,0,1)
swap.shape

(2, 1, 3)

# **CONCADENATE**

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
conc = np.concatenate((arr1,arr2))

In [ ]:
conc

array([1, 2, 3, 4, 5, 6, 7, 8])

# **STACK**

2 types of stack

v stack - vertical stack

h stack - horizontal stack



In [ ]:
vstack = np.vstack((arr1,arr2))
vstack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
hstack = np.hstack((arr1,arr2))
hstack

array([1, 2, 3, 4, 5, 6, 7, 8])

# SPLIT

2 types of split
hsplit

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
hsplit = np.hsplit((arr),3)
hsplit

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
vsplit = np.vsplit((arr),2)
vsplit

[array([[1, 2, 3]]), array([[4, 5, 6]])]

# **REPEAT AND TILE**

repeat = repeat every single element in an array

tile = repeat an array


In [ ]:
arr = np.array([1,2,3])
repeat = np.repeat(arr,3)
tile = np.tile(arr,3)
print(repeat)
print(tile)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


# **AGGREGATE FUNCTIONS**\

In [ ]:
#sum,mean,median,standard deviation,variance,minimum,maximum

In [ ]:
arr = np.array([1,2,3])
cumsum = np.cumsum(arr)
cumsum

array([1, 3, 6])

In [ ]:
cumprod = np.cumprod(arr)
cumprod

array([1, 2, 6])

# **CONDITIONAL BASED CHOICES**

WHERE and ARGWHERE

In [ ]:
where = np.where(arr<=2,"low","high")
where

array(['low', 'low', 'high'], dtype='<U4')

In [ ]:
argwhere = np.argwhere(arr<=2)
print(argwhere)
arr[argwhere]

[[0]
 [1]]


array([[1],
       [2]])

# **LOGICAL AND and LOGICAL OR**

In [ ]:
arr = np.array([1,2,3,4])
print(np.logical_and(arr<2,arr>=0))

[ True False False False]


In [ ]:
print(np.logical_or(arr<2,arr>=0))

[ True  True  True  True]


In [ ]:
print(np.logical_not(arr<2,arr>=0))

[False  True  True  True]


In [ ]:
print(np.logical_xor(arr<2,arr>=0))

[False  True  True  True]
